### ISSUE TITLE
unable to copy text

### ISSUE THREAD

**Issue by readyblue** [hqwrong/minitox#11]
Hi,

is there some way how could be possible to copy printed text. Like when I want to copy the ToxID, the selection of text keeps reseting itself (probably due to refresh of the window every time cursor blinks)

Thanks

**Comment by Nocturrne** [comment]
This sounds like an issue with the terminal you are using, not minitox.  I SSH into my linux VPS and use minitox from the command line with no problems.  You can copy and paste toxIDs, etc. as you normally would in any linux terminal.
